- hosts: localhost
  name: Terraform | Create GCP resources
  become: false
  connection: local
  gather_facts: false

  vars:
    terraform_gcp_dir: ../terraform/gcp

  pre_tasks:

  - name: Terraform | Init
    shell: |
      terraform init -no-color -reconfigure
    args:
      chdir: '{{ terraform_gcp_dir }}'
  - debug: var=inventory_file verbosity=2

  tasks:

  - name: Terraform | Plan changes
    shell: |
      terraform plan \
      -no-color
    args:
      chdir: '{{ terraform_gcp_dir }}'
    register: terraform_output_plan
    when: not terraform_apply | default(false) | bool

  - name: Terraform | Apply changes
    shell: |
      terraform apply \
      -no-color \
      -auto-approve
    args:
      chdir: '{{ terraform_gcp_dir }}'
    register: terraform_output_apply
    when: terraform_apply | default(false) | bool

  - debug:
      var: terraform_output_plan
    when: not terraform_apply | default(false) | bool
  - debug:
      var: terraform_output_apply
    when:  terraform_apply | default(false) | bool
