- hosts: localhost
  name: Jenkins | Create resources
  become: false
  connection: local
  gather_facts: false

  pre_tasks:

  - name: Kubectl config
    shell: |
      gcloud container clusters get-credentials tf-gke-helm --region {{ kubernetes_cluster_region }}

  tasks:

  - name: Deploy Jenkins Master ConfigMap
    shell: |
      kubectl create -f helm/jenkins/master/jenkins-master-casc.yaml

  - name: Create Jenkins Master Helm
    shell: |
      helm install --name jenkins-master stable/jenkins -f helm/jenkins/master/values.yml

  - name: Deploy Jenkins Team A ConfigMap
    shell: |
      kubectl create -f helm/jenkins/team_a/jenkins-teama-casc.yaml

  - name: Create Jenkins Team A Helm
    shell: |
      helm install --name jenkins-teama stable/jenkins -f helm/jenkins/team_a/values.yml

  - name: Deploy Jenkins Team B ConfigMap
    shell: |
      kubectl create -f helm/jenkins/team_b/jenkins-teamb-casc.yaml

  - name: Create Jenkins Team B Helm
    shell: |
      helm install --name jenkins-teamb stable/jenkins -f helm/jenkins/team_b/values.yml